on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 185.27.134.11
        username: if0_38153464
        password: ${{ secrets.ftp_password }}
        local-dir: './alok.html-5.me/htdocs/projects/'
